"""Initial

Revision ID: 45f5ab277a96
Revises: 
Create Date: 2022-03-10 19:00:50.646878

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '45f5ab277a96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__shows'))
    )
    op.create_table('watch_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__watch_history'))
    )
    op.create_index('ix__user_id', 'watch_history', ['user_id'], unique=False)
    op.create_table('watch_history_films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['watch_history.id'], name=op.f('fk__watch_history_films__id__watch_history'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__watch_history_films'))
    )
    op.create_table('watch_history_shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('first_episode', sa.SmallInteger(), nullable=True),
    sa.Column('last_episode', sa.SmallInteger(), nullable=True),
    sa.Column('season', sa.SmallInteger(), nullable=True),
    sa.Column('finished_season', sa.Boolean(), nullable=True),
    sa.Column('finished_show', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['watch_history.id'], name=op.f('fk__watch_history_shows__id__watch_history'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk__watch_history_shows__show_id__shows'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__watch_history_shows'))
    )
    op.create_table('watched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['watch_history.id'], name=op.f('fk__watched__id__watch_history'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__watched'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched')
    op.drop_table('watch_history_shows')
    op.drop_table('watch_history_films')
    op.drop_index('ix__user_id', table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_table('shows')
    # ### end Alembic commands ###
