"""Initial

Revision ID: a8835b25d433
Revises: 
Create Date: 2022-02-15 23:51:19.634838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8835b25d433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix__user_id_datetime', 'watched', ['user_id', 'datetime'], unique=False)
    op.create_index('ix__user_id_score', 'watched', ['user_id', 'score'], unique=False)
    op.create_table('watched_shows',
    sa.Column('watched_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.SmallInteger(), nullable=True),
    sa.Column('first_episode', sa.SmallInteger(), nullable=True),
    sa.Column('last_episode', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['watched_id'], ['watched.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_shows')
    op.drop_index('ix__user_id_score', table_name='watched')
    op.drop_index('ix__user_id_datetime', table_name='watched')
    op.drop_table('watched')
    # ### end Alembic commands ###
